// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ql1uwwohKwIRuuEy-RkZDvAq6u_OZAo',
    appId: '1:101849740538:web:a58acd7151761d6c6a8543',
    messagingSenderId: '101849740538',
    projectId: 'my-notes-8cbd6',
    authDomain: 'my-notes-8cbd6.firebaseapp.com',
    storageBucket: 'my-notes-8cbd6.appspot.com',
    measurementId: 'G-BNFVE65CCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvc0ERyVlGuhNPsGwUVcaiPUVtDvhBeUk',
    appId: '1:101849740538:android:01a145ecd4c547436a8543',
    messagingSenderId: '101849740538',
    projectId: 'my-notes-8cbd6',
    storageBucket: 'my-notes-8cbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7I5ZW3_1smjVImjBAzCH9LloaJGUFjI',
    appId: '1:101849740538:ios:939f102590c4f88f6a8543',
    messagingSenderId: '101849740538',
    projectId: 'my-notes-8cbd6',
    storageBucket: 'my-notes-8cbd6.appspot.com',
    iosClientId: '101849740538-j9kivf4idgs6mhcr70dnstk80g1voaka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7I5ZW3_1smjVImjBAzCH9LloaJGUFjI',
    appId: '1:101849740538:ios:939f102590c4f88f6a8543',
    messagingSenderId: '101849740538',
    projectId: 'my-notes-8cbd6',
    storageBucket: 'my-notes-8cbd6.appspot.com',
    iosClientId: '101849740538-j9kivf4idgs6mhcr70dnstk80g1voaka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
